# Use httptest

In this chapter we aim at adding HTTP testing infrastructure to exemplighratia using httptest.
For this, we start from the initial state of exemplighratia again. Back to square one!

## Setup

We need to install `{httptest}`.

First, we need to run `httptest::use_httptest()` which has a few effects:

* Adding httptest as a dependency to `DESCRIPTION`, under Suggests just like testthat.
* Creating a helper file under tests/testthat,

```r
library(httptest)
```

When testthat runs tests, files whose name starts with "helper" are always run first. This one makes sure to load httptest.

We shall tweak it a bit to be able 

* to automatically create mock files when the environment variable `RECORDING` is set to TRUE. This is one of many ways to record or not. We could even never record, and create mock files by hand instead (potentially copy-pasting from a real response, or the API docs)
* to fool our package into believing there is an API token around in contexts where there is not. Since tests will use recorded responses when we are not recording, we do not need an actual API token when not recording, but we need `gh_organizations()` to not stop because `Sys.getenv("GITHUB_PAT")` returns nothing.

```r

Sys.setenv(RECORDING = TRUE)

if (Sys.getenv("RECORDING")) {
  with_mock_api <- httptest::capture_requests
} else {
  Sys.setenv("GITHUB_PAT" = "foobar")
}

library(httptest)
```

## Actual testing

The key function will be `with_mock_api()`. With the helper as defined above, at the moment the function will be replaced with `httptest::capture_requests()` that saves the bodies of API responses in mock files automatically named by using the URL and method.

Later, when we write `Sys.setenv(RECORDING = FALSE)` in the helper, `httptest::with_mock_api()` ensures that instead of real API interactions, the mock files are used.

Let's tweak the test for `gh_api_status`, it now becomes

```r
with_mock_api({
  test_that("gh_api_status() works", {
    testthat::expect_type(gh_api_status(), "character")
  })
})
```

We only had to wrap the `test_that()` block.

After running the tests, we have a new file `tests/testthat/kctbh9vrtdwd.statuspage.io/api/v2/components.json.json`.

```json
{
    "page": {
        "id": "kctbh9vrtdwd",
        "name": "GitHub",
        "url": "https://www.githubstatus.com",
        "time_zone": "Etc/UTC",
        "updated_at": "2020-10-13T08:01:00.671Z"
    },
    "components": [
        {
            "id": "8l4ygp009s5s",
            "name": "Git Operations",
            "status": "operational",
            "created_at": "2017-01-31T20:05:05.370Z",
            "updated_at": "2020-09-24T02:32:00.916Z",
            "position": 1,
            "description": "Performance of git clones, pulls, pushes, and associated operations",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "brv1bkgrwx7q",
            "name": "API Requests",
            "status": "operational",
            "created_at": "2017-01-31T20:01:46.621Z",
            "updated_at": "2020-09-30T19:00:29.476Z",
            "position": 2,
            "description": "Requests for GitHub APIs",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "4230lsnqdsld",
            "name": "Webhooks",
            "status": "operational",
            "created_at": "2019-11-13T18:00:24.256Z",
            "updated_at": "2020-10-10T00:03:01.204Z",
            "position": 3,
            "description": "Real time HTTP callbacks of user-generated and system events",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "0l2p9nhqnxpd",
            "name": "Visit www.githubstatus.com for more information",
            "status": "operational",
            "created_at": "2018-12-05T19:39:40.838Z",
            "updated_at": "2020-04-02T21:56:21.954Z",
            "position": 4,
            "description": null,
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "kr09ddfgbfsf",
            "name": "Issues",
            "status": "operational",
            "created_at": "2017-01-31T20:01:46.638Z",
            "updated_at": "2020-10-10T00:02:16.199Z",
            "position": 5,
            "description": "Requests for Issues on GitHub.com",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "hhtssxt0f5v2",
            "name": "Pull Requests",
            "status": "operational",
            "created_at": "2020-09-02T15:39:06.329Z",
            "updated_at": "2020-10-10T00:02:49.033Z",
            "position": 6,
            "description": "Requests for Pull Requests on GitHub.com",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "br0l2tvcx85d",
            "name": "GitHub Actions",
            "status": "operational",
            "created_at": "2019-11-13T18:02:19.432Z",
            "updated_at": "2020-10-10T00:02:27.321Z",
            "position": 7,
            "description": "Workflows, Compute and Orchestration for GitHub Actions",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "st3j38cctv9l",
            "name": "GitHub Packages",
            "status": "operational",
            "created_at": "2019-11-13T18:02:40.064Z",
            "updated_at": "2020-09-08T15:50:32.845Z",
            "position": 8,
            "description": "API requests and webhook delivery for GitHub Packages",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        },
        {
            "id": "vg70hn9s2tyj",
            "name": "GitHub Pages",
            "status": "operational",
            "created_at": "2017-01-31T20:04:33.923Z",
            "updated_at": "2020-10-10T00:02:38.220Z",
            "position": 9,
            "description": "Frontend application and API servers for Pages builds",
            "showcase": false,
            "start_date": null,
            "group_id": null,
            "page_id": "kctbh9vrtdwd",
            "group": false,
            "only_show_if_degraded": false
        }
    ]
}

```


Let's tweak our other test, of `gh_organizations()`

```r
with_mock_api({
  test_that("gh_organizations works", {
    testthat::expect_type(gh_organizations(), "character")
  })
})
```

After we run it the mock file `tests/testthat/api.github.com/organizations-5377e8.json` was created.
It does not contain our API token despite our not making any configuration efforts, because by default httptest only saves the _body_ of the response.

Now in some cases secrets might be in the body of the response (in the case of the GitHub API, think of `gh::gh_whoami()`), in which case we would refer to httptest's article about ["Redacting sensitive information"](https://enpiar.com/r/httptest/articles/redacting.html), and add a line `set_redactor(~ gsub_response(., Sys.getenv('GITHUB_PAT'), "<<github_api_token>>"))` to `tests/testthat/helper.R` or to `inst/httptest/redact.R`.

After running the tests once, we have mock files at hand so can stop recording.
The helper file under `tests/testthat/helper.R` therefore becomes

```r

Sys.setenv(RECORDING = FALSE)

if (Sys.getenv("RECORDING")) {
  with_mock_api <- httptest::capture_requests
} else {
  Sys.setenv("GITHUB_PAT" = "foobar")
}

library(httptest)
```

## Summarize

* We set up httptest using `use_httptest()` and tweaking the helper file for easier recording.
* We wrapped our `test_that()` blocks into `with_mock_api()` and ran the tests a first time to generate mock files that hold the API interactions.

Now, how do we make sure this works?

* Turn off wifi, run the tests again. It works! Turn on wifi again.
* Open .Renviron (`usethis::edit_r_environ()`), edit "GITHUB_PAT" into "byeGITHUB_PAT", re-start R, run the tests again. It works! Fix your "GITHUB_PAT" token in .Renviron.

So we now have tests that no longer rely on an internet connection nor on having API credentials.

For the full list of changes applied to exemplighratia in this chapter, see [the pull request diff on GitHub](https://github.com/maelle/exemplighratia/pull/1/files).

**How do we get there with presser! We'll get there soon but first let's compare mocking with vcr and httptest in the next chapter**